package hpdf

/*
#cgo LDFLAGS: -lhpdf -lpng -lz
#include "hpdf.h"
*/
import "C"

type ErrorCode int

const (
	ERR_ARRAY_COUNT_ERR              ErrorCode = C.HPDF_ARRAY_COUNT_ERR
	ERR_ARRAY_ITEM_NOT_FOUND         ErrorCode = C.HPDF_ARRAY_ITEM_NOT_FOUND
	ERR_ARRAY_ITEM_UNEXPECTED_TYPE   ErrorCode = C.HPDF_ARRAY_ITEM_UNEXPECTED_TYPE
	ERR_BINARY_LENGTH_ERR            ErrorCode = C.HPDF_BINARY_LENGTH_ERR
	ERR_CANNOT_GET_PALLET            ErrorCode = C.HPDF_CANNOT_GET_PALLET
	ERR_DICT_COUNT_ERR               ErrorCode = C.HPDF_DICT_COUNT_ERR
	ERR_DICT_ITEM_NOT_FOUND          ErrorCode = C.HPDF_DICT_ITEM_NOT_FOUND
	ERR_DICT_ITEM_UNEXPECTED_TYPE    ErrorCode = C.HPDF_DICT_ITEM_UNEXPECTED_TYPE
	ERR_DICT_STREAM_LENGTH_NOT_FOUND ErrorCode = C.HPDF_DICT_STREAM_LENGTH_NOT_FOUND
	ERR_DOC_ENCRYPTDICT_NOT_FOUND    ErrorCode = C.HPDF_DOC_ENCRYPTDICT_NOT_FOUND
	ERR_DOC_INVALID_OBJECT           ErrorCode = C.HPDF_DOC_INVALID_OBJECT
	ERR_DUPLICATE_REGISTRATION       ErrorCode = C.HPDF_DUPLICATE_REGISTRATION
	ERR_EXCEED_JWW_CODE_NUM_LIMIT    ErrorCode = C.HPDF_EXCEED_JWW_CODE_NUM_LIMIT
	ERR_ENCRYPT_INVALID_PASSWORD     ErrorCode = C.HPDF_ENCRYPT_INVALID_PASSWORD
	ERR_ERR_UNKNOWN_CLASS            ErrorCode = C.HPDF_ERR_UNKNOWN_CLASS
	ERR_EXCEED_GSTATE_LIMIT          ErrorCode = C.HPDF_EXCEED_GSTATE_LIMIT
	ERR_FAILD_TO_ALLOC_MEM           ErrorCode = C.HPDF_FAILD_TO_ALLOC_MEM
	ERR_FILE_IO_ERROR                ErrorCode = C.HPDF_FILE_IO_ERROR
	ERR_FILE_OPEN_ERROR              ErrorCode = C.HPDF_FILE_OPEN_ERROR
	ERR_FONT_EXISTS                  ErrorCode = C.HPDF_FONT_EXISTS
	ERR_FONT_INVALID_WIDTHS_TABLE    ErrorCode = C.HPDF_FONT_INVALID_WIDTHS_TABLE
	ERR_INVALID_AFM_HEADER           ErrorCode = C.HPDF_INVALID_AFM_HEADER
	ERR_INVALID_ANNOTATION           ErrorCode = C.HPDF_INVALID_ANNOTATION
	ERR_INVALID_BIT_PER_COMPONENT    ErrorCode = C.HPDF_INVALID_BIT_PER_COMPONENT
	ERR_INVALID_CHAR_MATRICS_DATA    ErrorCode = C.HPDF_INVALID_CHAR_MATRICS_DATA
	ERR_INVALID_COLOR_SPACE          ErrorCode = C.HPDF_INVALID_COLOR_SPACE
	ERR_INVALID_COMPRESSION_MODE     ErrorCode = C.HPDF_INVALID_COMPRESSION_MODE
	ERR_INVALID_DATE_TIME            ErrorCode = C.HPDF_INVALID_DATE_TIME
	ERR_INVALID_DESTINATION          ErrorCode = C.HPDF_INVALID_DESTINATION
	ERR_INVALID_DOCUMENT             ErrorCode = C.HPDF_INVALID_DOCUMENT
	ERR_INVALID_DOCUMENT_STATE       ErrorCode = C.HPDF_INVALID_DOCUMENT_STATE
	ERR_INVALID_ENCODER              ErrorCode = C.HPDF_INVALID_ENCODER
	ERR_INVALID_ENCODER_TYPE         ErrorCode = C.HPDF_INVALID_ENCODER_TYPE
	ERR_INVALID_ENCODING_NAME        ErrorCode = C.HPDF_INVALID_ENCODING_NAME
	ERR_INVALID_ENCRYPT_KEY_LEN      ErrorCode = C.HPDF_INVALID_ENCRYPT_KEY_LEN
	ERR_INVALID_FONTDEF_DATA         ErrorCode = C.HPDF_INVALID_FONTDEF_DATA
	ERR_INVALID_FONTDEF_TYPE         ErrorCode = C.HPDF_INVALID_FONTDEF_TYPE
	ERR_INVALID_FONT_NAME            ErrorCode = C.HPDF_INVALID_FONT_NAME
	ERR_INVALID_IMAGE                ErrorCode = C.HPDF_INVALID_IMAGE
	ERR_INVALID_JPEG_DATA            ErrorCode = C.HPDF_INVALID_JPEG_DATA
	ERR_INVALID_N_DATA               ErrorCode = C.HPDF_INVALID_N_DATA
	ERR_INVALID_OBJECT               ErrorCode = C.HPDF_INVALID_OBJECT
	ERR_INVALID_OBJ_ID               ErrorCode = C.HPDF_INVALID_OBJ_ID
	ERR_INVALID_OPERATION            ErrorCode = C.HPDF_INVALID_OPERATION
	ERR_INVALID_OUTLINE              ErrorCode = C.HPDF_INVALID_OUTLINE
	ERR_INVALID_PAGE                 ErrorCode = C.HPDF_INVALID_PAGE
	ERR_INVALID_PAGES                ErrorCode = C.HPDF_INVALID_PAGES
	ERR_INVALID_PARAMETER            ErrorCode = C.HPDF_INVALID_PARAMETER
	ERR_INVALID_PNG_IMAGE            ErrorCode = C.HPDF_INVALID_PNG_IMAGE
	ERR_INVALID_STREAM               ErrorCode = C.HPDF_INVALID_STREAM
	ERR_MISSING_FILE_NAME_ENTRY      ErrorCode = C.HPDF_MISSING_FILE_NAME_ENTRY
	ERR_INVALID_TTC_FILE             ErrorCode = C.HPDF_INVALID_TTC_FILE
	ERR_INVALID_TTC_INDEX            ErrorCode = C.HPDF_INVALID_TTC_INDEX
	ERR_INVALID_WX_DATA              ErrorCode = C.HPDF_INVALID_WX_DATA
	ERR_ITEM_NOT_FOUND               ErrorCode = C.HPDF_ITEM_NOT_FOUND
	ERR_LIBPNG_ERROR                 ErrorCode = C.HPDF_LIBPNG_ERROR
	ERR_NAME_INVALID_VALUE           ErrorCode = C.HPDF_NAME_INVALID_VALUE
	ERR_NAME_OUT_OF_RANGE            ErrorCode = C.HPDF_NAME_OUT_OF_RANGE
	ERR_PAGES_MISSING_KIDS_ENTRY     ErrorCode = C.HPDF_PAGES_MISSING_KIDS_ENTRY
	ERR_PAGE_CANNOT_FIND_OBJECT      ErrorCode = C.HPDF_PAGE_CANNOT_FIND_OBJECT
	ERR_PAGE_CANNOT_GET_ROOT_PAGES   ErrorCode = C.HPDF_PAGE_CANNOT_GET_ROOT_PAGES
	ERR_PAGE_CANNOT_RESTORE_GSTATE   ErrorCode = C.HPDF_PAGE_CANNOT_RESTORE_GSTATE
	ERR_PAGE_CANNOT_SET_PARENT       ErrorCode = C.HPDF_PAGE_CANNOT_SET_PARENT
	ERR_PAGE_FONT_NOT_FOUND          ErrorCode = C.HPDF_PAGE_FONT_NOT_FOUND
	ERR_PAGE_INVALID_FONT            ErrorCode = C.HPDF_PAGE_INVALID_FONT
	ERR_PAGE_INVALID_FONT_SIZE       ErrorCode = C.HPDF_PAGE_INVALID_FONT_SIZE
	ERR_PAGE_INVALID_GMODE           ErrorCode = C.HPDF_PAGE_INVALID_GMODE
	ERR_PAGE_INVALID_INDEX           ErrorCode = C.HPDF_PAGE_INVALID_INDEX
	ERR_PAGE_INVALID_ROTATE_VALUE    ErrorCode = C.HPDF_PAGE_INVALID_ROTATE_VALUE
	ERR_PAGE_INVALID_SIZE            ErrorCode = C.HPDF_PAGE_INVALID_SIZE
	ERR_PAGE_INVALID_XOBJECT         ErrorCode = C.HPDF_PAGE_INVALID_XOBJECT
	ERR_PAGE_OUT_OF_RANGE            ErrorCode = C.HPDF_PAGE_OUT_OF_RANGE
	ERR_REAL_OUT_OF_RANGE            ErrorCode = C.HPDF_REAL_OUT_OF_RANGE
	ERR_STREAM_EOF                   ErrorCode = C.HPDF_STREAM_EOF
	ERR_STREAM_READLN_CONTINUE       ErrorCode = C.HPDF_STREAM_READLN_CONTINUE
	ERR_STRING_OUT_OF_RANGE          ErrorCode = C.HPDF_STRING_OUT_OF_RANGE
	ERR_THIS_FUNC_WAS_SKIPPED        ErrorCode = C.HPDF_THIS_FUNC_WAS_SKIPPED
	ERR_TTF_CANNOT_EMBEDDING_FONT    ErrorCode = C.HPDF_TTF_CANNOT_EMBEDDING_FONT
	ERR_TTF_INVALID_CMAP             ErrorCode = C.HPDF_TTF_INVALID_CMAP
	ERR_TTF_INVALID_FOMAT            ErrorCode = C.HPDF_TTF_INVALID_FOMAT
	ERR_TTF_MISSING_TABLE            ErrorCode = C.HPDF_TTF_MISSING_TABLE
	ERR_UNSUPPORTED_FONT_TYPE        ErrorCode = C.HPDF_UNSUPPORTED_FONT_TYPE
	ERR_UNSUPPORTED_FUNC             ErrorCode = C.HPDF_UNSUPPORTED_FUNC
	ERR_UNSUPPORTED_JPEG_FORMAT      ErrorCode = C.HPDF_UNSUPPORTED_JPEG_FORMAT
	ERR_UNSUPPORTED_TYPE1_FONT       ErrorCode = C.HPDF_UNSUPPORTED_TYPE1_FONT
	ERR_XREF_COUNT_ERR               ErrorCode = C.HPDF_XREF_COUNT_ERR
	ERR_ZLIB_ERROR                   ErrorCode = C.HPDF_ZLIB_ERROR
	ERR_INVALID_PAGE_INDEX           ErrorCode = C.HPDF_INVALID_PAGE_INDEX
	ERR_INVALID_URI                  ErrorCode = C.HPDF_INVALID_URI
	ERR_ANNOT_INVALID_ICON           ErrorCode = C.HPDF_ANNOT_INVALID_ICON
	ERR_ANNOT_INVALID_BORDER_STYLE   ErrorCode = C.HPDF_ANNOT_INVALID_BORDER_STYLE
	ERR_PAGE_INVALID_DIRECTION       ErrorCode = C.HPDF_PAGE_INVALID_DIRECTION
	ERR_INVALID_FONT                 ErrorCode = C.HPDF_INVALID_FONT
)
