package hpdf

var ErrorMessages = map[ErrorCode]string{
	ERR_ARRAY_COUNT_ERR:              "Internal error. Data consistency was lost",
	ERR_ARRAY_ITEM_NOT_FOUND:         "Internal error. Data consistency was lost",
	ERR_ARRAY_ITEM_UNEXPECTED_TYPE:   "Internal error. Data consistency was lost",
	ERR_BINARY_LENGTH_ERR:            "Data length > HPDF_LIMIT_MAX_STRING_LEN",
	ERR_CANNOT_GET_PALLET:            "Cannot get pallet data from PNG image",
	ERR_DICT_COUNT_ERR:               "Dictionary elements > HPDF_LIMIT_MAX_DICT_ELEMENT",
	ERR_DICT_ITEM_NOT_FOUND:          "Internal error. Data consistency was lost",
	ERR_DICT_ITEM_UNEXPECTED_TYPE:    "Internal error. Data consistency was lost",
	ERR_DICT_STREAM_LENGTH_NOT_FOUND: "Internal error. Data consistency was lost",
	ERR_DOC_ENCRYPTDICT_NOT_FOUND:    "HPDF_SetEncryptMode() or HPDF_SetPermission() called before password set",
	ERR_DOC_INVALID_OBJECT:           "Internal error. Data consistency was lost",
	ERR_DUPLICATE_REGISTRATION:       "Tried to re-register a registered font",
	ERR_EXCEED_JWW_CODE_NUM_LIMIT:    "Cannot register a character to the Japanese word wrap characters list",
	ERR_ENCRYPT_INVALID_PASSWORD:     "Tried to set the owner password to NULL or Owner and user password are the same",
	ERR_ERR_UNKNOWN_CLASS:            "Internal error. Data consistency was lost",
	ERR_EXCEED_GSTATE_LIMIT:          "Stack depth > HPDF_LIMIT_MAX_GSTATE",
	ERR_FAILD_TO_ALLOC_MEM:           "Memory allocation failed",
	ERR_FILE_IO_ERROR:                "File processing failed. (Detailed code is set.)",
	ERR_FILE_OPEN_ERROR:              "Cannot open a file. (Detailed code is set.)",
	ERR_FONT_EXISTS:                  "Tried to load a font that has been registered",
	ERR_FONT_INVALID_WIDTHS_TABLE:    "Font-file format is invalid or Internal error. Data consistency was lost",
	ERR_INVALID_AFM_HEADER:           "Cannot recognize header of afm file",
	ERR_INVALID_ANNOTATION:           "Specified annotation handle is invalid",
	ERR_INVALID_BIT_PER_COMPONENT:    "Bit-per-component of a image which was set as mask-image is invalid",
	ERR_INVALID_CHAR_MATRICS_DATA:    "Cannot recognize char-matrics-data of afm file",
	ERR_INVALID_COLOR_SPACE:          "Invalid color_space parameter of HPDF_LoadRawImage, Color-space of a image which was set as mask-image is invalid or Invoked function invalid in present color-space",
	ERR_INVALID_COMPRESSION_MODE:     "Invalid value set when invoking HPDF_SetCommpressionMode()",
	ERR_INVALID_DATE_TIME:            "An invalid date-time value was set",
	ERR_INVALID_DESTINATION:          "An invalid destination handle was set",
	ERR_INVALID_DOCUMENT:             "An invalid document handle was set",
	ERR_INVALID_DOCUMENT_STATE:       "Function invalid in the present state was invoked",
	ERR_INVALID_ENCODER:              "An invalid encoder handle was set",
	ERR_INVALID_ENCODER_TYPE:         "Combination between font and encoder is wrong",
	ERR_INVALID_ENCODING_NAME:        "An Invalid encoding name is specified",
	ERR_INVALID_ENCRYPT_KEY_LEN:      "Encryption key length is invalid",
	ERR_INVALID_FONTDEF_DATA:         "An invalid font handle was set or Unsupported font format",
	ERR_INVALID_FONTDEF_TYPE:         "Internal error. Data consistency was lost",
	ERR_INVALID_FONT_NAME:            "Font with the specified name is not found",
	ERR_INVALID_IMAGE:                "Unsupported image format",
	ERR_INVALID_JPEG_DATA:            "Unsupported image format",
	ERR_INVALID_N_DATA:               "Cannot read a postscript-name from an afm file",
	ERR_INVALID_OBJECT:               "An invalid object is set or Internal error. Data consistency was lost",
	ERR_INVALID_OBJ_ID:               "Internal error. Data consistency was lost",
	ERR_INVALID_OPERATION:            "Invoked HPDF_Image_SetColorMask() against the image-object which was set a mask-image",
	ERR_INVALID_OUTLINE:              "An invalid outline-handle was specified",
	ERR_INVALID_PAGE:                 "An invalid page-handle was specified",
	ERR_INVALID_PAGES:                "An invalid pages-handle was specified. (internal error)",
	ERR_INVALID_PARAMETER:            "An invalid value is set",
	ERR_INVALID_PNG_IMAGE:            "Invalid PNG image format",
	ERR_INVALID_STREAM:               "Internal error. Data consistency was lost",
	ERR_MISSING_FILE_NAME_ENTRY:      "Internal error. \"_FILE_NAME\" entry for delayed loading is missing",
	ERR_INVALID_TTC_FILE:             "Invalid .TTC file format",
	ERR_INVALID_TTC_INDEX:            "Index parameter > number of included fonts",
	ERR_INVALID_WX_DATA:              "Cannot read a width-data from an afm file",
	ERR_ITEM_NOT_FOUND:               "Internal error. Data consistency was lost",
	ERR_LIBPNG_ERROR:                 "Error returned from PNGLIB while loading image",
	ERR_NAME_INVALID_VALUE:           "Internal error. Data consistency was lost",
	ERR_NAME_OUT_OF_RANGE:            "Internal error. Data consistency was lost",
	ERR_PAGES_MISSING_KIDS_ENTRY:     "Internal error. Data consistency was lost",
	ERR_PAGE_CANNOT_FIND_OBJECT:      "Internal error. Data consistency was lost",
	ERR_PAGE_CANNOT_GET_ROOT_PAGES:   "Internal error. Data consistency was lost",
	ERR_PAGE_CANNOT_RESTORE_GSTATE:   "There are no graphics-states to be restored",
	ERR_PAGE_CANNOT_SET_PARENT:       "Internal error. Data consistency was lost",
	ERR_PAGE_FONT_NOT_FOUND:          "The current font is not set",
	ERR_PAGE_INVALID_FONT:            "An invalid font-handle was specified",
	ERR_PAGE_INVALID_FONT_SIZE:       "An invalid font-size was set",
	ERR_PAGE_INVALID_GMODE:           "See Graphics mode",
	ERR_PAGE_INVALID_INDEX:           "Internal error. Data consistency was lost",
	ERR_PAGE_INVALID_ROTATE_VALUE:    "Specified value is not multiple of 90",
	ERR_PAGE_INVALID_SIZE:            "An invalid page-size was set",
	ERR_PAGE_INVALID_XOBJECT:         "An invalid image-handle was set",
	ERR_PAGE_OUT_OF_RANGE:            "The specified value is out of range",
	ERR_REAL_OUT_OF_RANGE:            "The specified value is out of range",
	ERR_STREAM_EOF:                   "Unexpected EOF marker was detected",
	ERR_STREAM_READLN_CONTINUE:       "Internal error. Data consistency was lost",
	ERR_STRING_OUT_OF_RANGE:          "The length of the text is too long",
	ERR_THIS_FUNC_WAS_SKIPPED:        "Function not executed because of other errors",
	ERR_TTF_CANNOT_EMBEDDING_FONT:    "Font cannot be embedded. (license restriction)",
	ERR_TTF_INVALID_CMAP:             "Unsupported ttf format. (cannot find unicode cmap)",
	ERR_TTF_INVALID_FOMAT:            "Unsupported ttf format",
	ERR_TTF_MISSING_TABLE:            "Unsupported ttf format. (cannot find a necessary table)",
	ERR_UNSUPPORTED_FONT_TYPE:        "Internal error. Data consistency was lost",
	ERR_UNSUPPORTED_FUNC:             "Library not configured to use PNGLIB or Internal error. Data consistency was lost",
	ERR_UNSUPPORTED_JPEG_FORMAT:      "Unsupported JPEG format",
	ERR_UNSUPPORTED_TYPE1_FONT:       "Failed to parse .PFB file",
	ERR_XREF_COUNT_ERR:               "Internal error. Data consistency was lost",
	ERR_ZLIB_ERROR:                   "Error while executing ZLIB function",
	ERR_INVALID_PAGE_INDEX:           "An invalid page index was passed",
	ERR_INVALID_URI:                  "An invalid URI was set",
	ERR_ANNOT_INVALID_ICON:           "An invalid icon was set",
	ERR_ANNOT_INVALID_BORDER_STYLE:   "An invalid border-style was set",
	ERR_PAGE_INVALID_DIRECTION:       "An invalid page-direction was set",
	ERR_INVALID_FONT:                 "An invalid font-handle was specified",
}
